//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnection_DBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empNo { get; set; }
        public string empName { get; set; }
        public Nullable<int> empSal { get; set; }
    }
}
